### ISSUE TITLE
Crash aléatoires (?)

### ISSUE THREAD

**Issue by kvnco** [barbogogo/leedReader#67]
Bonjour,

Dans la dernière version de l'application je rencontre plusieurs crash, qui semblent aléatoires.
Ceux-ci sont d'autant plus frustrants qu'ils surviennent généralement lors du clic sur un élément. Celui-ci est alors marqué comme lu… et pas affiché puisque l'appli se plante. Ils ne sont donc pas facilement retrouvable.

Ils semblent survenir plus facilement après un ou plusieurs scrolls (et donc chargement d'items en lazy-loading) mais ce n'est pas systématique.

Voici 2 traces (correspondant donc à 2 bugs) que j'ai pu réaliser dans une VM :
## Trace 1

11-16 17:28:59.065: D/AndroidRuntime(1860): Shutting down VM
11-16 17:28:59.065: W/dalvikvm(1860): threadid=1: thread exiting with uncaught exception (group=0xb3f7e648)
11-16 17:28:59.075: E/AndroidRuntime(1860): FATAL EXCEPTION: main
11-16 17:28:59.075: E/AndroidRuntime(1860): java.lang.NullPointerException
11-16 17:28:59.075: E/AndroidRuntime(1860):     at com.barbogogo.leedreader.WebviewAdapter.setWebView(WebviewAdapter.java:73)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at com.barbogogo.leedreader.WebviewAdapter.instantiateItem(WebviewAdapter.java:45)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at android.support.v4.view.PagerAdapter.instantiateItem(PagerAdapter.java:110)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:832)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at android.support.v4.view.ViewPager.populate(ViewPager.java:982)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at android.support.v4.view.ViewPager.populate(ViewPager.java:914)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:442)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at com.barbogogo.leedreader.FeedAdapter$1.onClick(FeedAdapter.java:135)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at android.view.View.performClick(View.java:4240)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at android.view.View$PerformClick.run(View.java:17721)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at android.os.Handler.handleCallback(Handler.java:730)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at android.os.Handler.dispatchMessage(Handler.java:92)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at android.os.Looper.loop(Looper.java:137)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at android.app.ActivityThread.main(ActivityThread.java:5103)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at java.lang.reflect.Method.invokeNative(Native Method)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at java.lang.reflect.Method.invoke(Method.java:525)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
11-16 17:28:59.075: E/AndroidRuntime(1860):     at dalvik.system.NativeStart.main(Native Method)
## Trace 2

11-16 17:16:45.293: D/AndroidRuntime(1287): Shutting down VM
11-16 17:16:45.293: W/dalvikvm(1287): threadid=1: thread exiting with uncaught exception (group=0xb4a93b90)
11-16 17:16:45.433: E/AndroidRuntime(1287): FATAL EXCEPTION: main
11-16 17:16:45.433: E/AndroidRuntime(1287): Process: com.leed.reader, PID: 1287
11-16 17:16:45.433: E/AndroidRuntime(1287): java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131427337, class android.widget.ListView) with Adapter(class android.widget.HeaderViewListAdapter)]
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.widget.ListView.layoutChildren(ListView.java:1555)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.widget.AbsListView.onTouchMove(AbsListView.java:3549)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.widget.AbsListView.onTouchEvent(AbsListView.java:3424)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.View.dispatchTouchEvent(View.java:7690)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2066)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.app.Activity.dispatchTouchEvent(Activity.java:2457)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2014)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.View.dispatchPointerEvent(View.java:7870)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3919)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3808)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3406)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3456)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3425)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3510)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3433)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3567)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3406)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3456)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3425)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3433)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3406)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5520)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5500)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5471)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5594)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:182)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:174)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5573)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5613)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.Choreographer.doCallbacks(Choreographer.java:562)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.Choreographer.doFrame(Choreographer.java:530)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.os.Handler.handleCallback(Handler.java:733)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.os.Handler.dispatchMessage(Handler.java:95)
11-16 17:16:45.433: E/AndroidRuntime(1287):     at android.os.Looper.loop(Looper.java:137
11-16 17:16:49.153: I/Process(1287): Sending signal. PID: 1287 SIG: 9

**Comment by barbogogo** [comment]
Bonjour @kvnco,
Merci pour ces traces. Je vais regarder de plus près. Effectivement c'est gênant car les flux sont marqués comme lus et ils ne s'affichent plus sur LeedReader...
